27 create crud operations for orders. #closes 27
DimK10/hotel-management-application pull request #29
Opened 2022-11-08 19:22 UTC by georgepoul

2022-11-15 08:03 UTC, DimK10 requested changes

2022-11-15 08:03 UTC, DimK10 commented on src/main/java/com/sphy/hotelmanagementapplication/converter/ClientDTOToClient.java
> +            client.getOrders().add(orderDTOToOrder.converter(orderDTO));
I think you need to add @Transactional, because getOrders() might throw LazyInitiallizationException

2022-11-15 08:03 UTC, DimK10 commented on src/main/java/com/sphy/hotelmanagementapplication/converter/ClientToClientDTO.java
> +            clientDTO.getOrders().add(orderToOrderDTO.converter(order));
I think you need to add @transactional, because getOrders() might throw LazyInitiallizationException

2022-11-15 08:03 UTC, DimK10 commented on src/main/java/com/sphy/hotelmanagementapplication/converter/RoomDTOToRoom.java
> +            room.getOrders().add(orderDTOToOrder.converter(orderDTO));
I think you need to add @transactional, because getOrders() might throw LazyInitiallizationException

2022-11-15 08:03 UTC, DimK10 commented on src/main/java/com/sphy/hotelmanagementapplication/converter/RoomToRoomDTO.java
> +        if (!(room.getHotel() == null)) {
I think you need to add @transactional, because getOrders() might throw LazyInitiallizationException

2022-11-15 08:03 UTC, DimK10 commented on src/main/java/com/sphy/hotelmanagementapplication/converter/RoomToRoomDTO.java
> +            Optional<Hotel> hotel = hotelRepository.findById(room.getHotel().getId());
getHotel() might be null here, so we have to check if it is not null

2022-11-15 08:03 UTC, DimK10 commented on src/main/java/com/sphy/hotelmanagementapplication/domain/Client.java
> +    }
super.setId(id) because the id wont be passed to object otherwise

2022-11-15 08:03 UTC, DimK10 commented on src/main/java/com/sphy/hotelmanagementapplication/domain/Order.java
> +@Entity(name = "orders")
I think the name in @Entity is redundant, if we add name in @Table

2022-11-15 08:03 UTC, DimK10 commented on src/main/java/com/sphy/hotelmanagementapplication/service/OrderService.java
> +        if (!client.isPresent()){
There is also the method isEmpty()

2022-11-15 08:03 UTC, DimK10 commented on src/main/java/com/sphy/hotelmanagementapplication/service/OrderService.java
> +                orderRepository.save(order);
Get the savd order and send it to controller

2022-11-15 08:03 UTC, DimK10 commented on src/main/java/com/sphy/hotelmanagementapplication/service/OrderService.java
> +        if (!order.isPresent()){
also there is the isEmpty()

2022-11-15 08:03 UTC, DimK10 commented on src/main/java/com/sphy/hotelmanagementapplication/service/RoomService.java
> +            roomRepository.save(room);
We need to return the room from save method not the initial

2022-11-15 08:03 UTC, DimK10 commented on src/main/java/com/sphy/hotelmanagementapplication/service/RoomService.java
> +        roomRepository.saveAll(rooms);
We need to return the list of rooms that were saved, not the initial

2022-11-15 08:03 UTC, DimK10 commented on src/test/java/com/sphy/hotelmanagementapplication/controller/OrderControllerTest.java
> +        mockMvc.perform(get("/api/orderId/1"))
its better to use parameter here, that is put also in Given section

2022-11-15 08:03 UTC, DimK10 commented on src/test/java/com/sphy/hotelmanagementapplication/service/OrderServiceTest.java
> +        when(orderRepository.findById(anyLong())).thenReturn(Optional.ofNullable(order));
no need to use ofNullable here because we know that the object we test exists - we can just use Optional.of(object)

2022-11-15 08:06 UTC, georgepoul commented on src/main/java/com/sphy/hotelmanagementapplication/domain/Client.java
> +    }
It's only for the tests

2022-11-15 08:08 UTC, georgepoul commented on src/main/java/com/sphy/hotelmanagementapplication/domain/Order.java
> +@Entity(name = "orders")
It is important for the query

2022-11-16 06:43 UTC, DimK10 approved these changes

2022-11-16 06:47 UTC, merged