28 add tests to converters close #28
DimK10/hotel-management-application pull request #34
Opened 2022-11-27 17:34 UTC by georgepoul

2022-11-28 11:18 UTC, DimK10 requested changes
Please check comments

2022-11-28 11:18 UTC, DimK10 commented on src/main/java/com/sphy/hotelmanagementapplication/converter/OrderToOrderDTO.java
> +        if (order.getClient().getId() != null){
You also need to check if getClient() is null

2022-11-28 11:18 UTC, DimK10 commented on src/main/java/com/sphy/hotelmanagementapplication/dto/RoomDTO.java
> +    }
add super(l)

2022-11-28 11:18 UTC, DimK10 commented on src/test/java/com/sphy/hotelmanagementapplication/converters/AdminToAdminDTOTest.java
> +        assertEquals(adminDTO.getId() , adminToAdminDTO.converter(admin).getId());
Please check all properties because its the main purpose of a converter

2022-11-28 11:18 UTC, DimK10 commented on src/test/java/com/sphy/hotelmanagementapplication/converters/ClientToClientDTOTest.java
> +        assertEquals(clientDTO.getId() , clientToClientDTO.converter(client).getId());
Please check all properties because its the main purpose of a converter

2022-11-28 11:18 UTC, DimK10 commented on src/test/java/com/sphy/hotelmanagementapplication/converters/HotelDTOToHotelTest.java
> +        when(adminRepository.findById(anyLong())).thenReturn(Optional.ofNullable(admin));
Optional.of() instead of Optional.ofNullable(), since you pass a non null object anyway

2022-11-28 11:18 UTC, DimK10 commented on src/test/java/com/sphy/hotelmanagementapplication/converters/HotelToHotelDTOTest.java
> +        assertEquals(hotelDTO.getId() , hotelToHotelDTO.converter(hotel).getId());
Please check all properties because its the main purpose of a converter

2022-11-28 11:18 UTC, DimK10 commented on src/test/java/com/sphy/hotelmanagementapplication/converters/OrderToOrderDTOTest.java
> +        assertEquals(orderDTO.getId() , orderToOrderDTO.converter(order).getId());
Please check all properties because its the main purpose of a converter

2022-11-28 11:18 UTC, DimK10 commented on src/test/java/com/sphy/hotelmanagementapplication/converters/RoomToRoomDTOTest.java
> +        assertEquals(roomDTO.getId() , roomToRoomDTO.converter(room).getId());
Please check all properties because its the main purpose of a converter

2022-11-28 18:04 UTC, georgepoul commented on src/main/java/com/sphy/hotelmanagementapplication/dto/RoomDTO.java
> +    }
It's a DTO and it has his own id

2022-11-28 18:07 UTC, georgepoul commented on src/main/java/com/sphy/hotelmanagementapplication/converter/OrderToOrderDTO.java
> +        if (order.getClient().getId() != null){
It's not the same if I check that the id of the client that make the order is not null;
Because it can't be saved a client if he has not an id

2022-12-01 10:10 UTC, DimK10 approved these changes

2022-12-01 10:11 UTC, merged