32 create pagination urls for list of hotels and rooms close #32
DimK10/hotel-management-application pull request #35
Opened 2022-11-30 17:28 UTC by georgepoul

2022-12-01 11:24 UTC, DimK10 requested changes
Please check the comments

2022-12-01 11:24 UTC, DimK10 commented on src/test/java/com/sphy/hotelmanagementapplication/service/HotelServiceIT.java
> +
Please add a check in some of the fields in one of the hotelDTO's returned. This test confirms that the elements returned as faras the list size is ok, but we should do a basic check on those elements

2022-12-01 11:24 UTC, DimK10 commented on src/test/java/com/sphy/hotelmanagementapplication/service/HotelServiceTest.java
> -        void getHotels() throws Exception {
why did you remove those tests?

2022-12-01 11:24 UTC, DimK10 commented on src/test/java/com/sphy/hotelmanagementapplication/service/HotelServiceTest.java
> +        void getHotels(){
This is not countHotels

2022-12-01 11:24 UTC, DimK10 commented on src/test/java/com/sphy/hotelmanagementapplication/service/RoomServiceIT.java
> +            assertEquals(expected, hotelDTOS.size());
The same as HotelServiceIT comment

2022-12-01 11:24 UTC, DimK10 commented on src/test/java/com/sphy/hotelmanagementapplication/service/RoomServiceTest.java
> -	void getRooms() throws Exception {
Again, this test is for all rooms not their count why did you remove it

2022-12-01 15:40 UTC, georgepoul commented on src/test/java/com/sphy/hotelmanagementapplication/service/HotelServiceTest.java
> -        void getHotels() throws Exception {
I have made an IT test for that.

2022-12-01 15:40 UTC, georgepoul commented on src/test/java/com/sphy/hotelmanagementapplication/service/RoomServiceTest.java
> -	void getRooms() throws Exception {
I have made an IT test for that.

2022-12-03 11:55 UTC, DimK10 approved these changes

2022-12-03 11:56 UTC, merged